apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: czojwuki1-java-springboot
  janus-idp.io/tekton: czojwuki1-java-springboot
  backstage.io/kubernetes-id: czojwuki1-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: czojwuki1-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
